allowBuilds:
  '@smithery/cli': true
  esbuild: true
  keytar: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/client@2.0.0'
  - '@modelcontextprotocol/core@2.0.0'
  - '@modelcontextprotocol/server@2.0.0'
