export {
	handleNpmVersions,
	handleNpmLatest,
	handleNpmDeps,
	handleNpmTypes,
	handleNpmSize,
	handleNpmVulnerabilities,
	handleNpmTrends,
	handleNpmCompare,
	handleNpmMaintainers,
	handleNpmScore,
	handleNpmPackageReadme,
	handleNpmSearch,
	handleNpmLicenseCompatibility,
	handleNpmRepoStats,
	handleNpmDeprecated,
	handleNpmChangelogAnalysis,
	handleNpmAlternatives,
	handleNpmQuality,
	handleNpmMaintenance,
} from '../../index.js';
