export {
	handleNpmAlternatives,
	handleNpmChangelogAnalysis,
	handleNpmCompare,
	handleNpmDeprecated,
	handleNpmDeps,
	handleNpmLatest,
	handleNpmLicenseCompatibility,
	handleNpmMaintainers,
	handleNpmMaintenance,
	handleNpmPackageReadme,
	handleNpmQuality,
	handleNpmRepoStats,
	handleNpmScore,
	handleNpmSearch,
	handleNpmSize,
	handleNpmTrends,
	handleNpmTypes,
	handleNpmVersions,
	handleNpmVulnerabilities,
} from '../../index.js';
