# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mcp-server

on:
    push:
        branches: [main]
    pull_request:
        branches: ["*"]

jobs:
    quality:
        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                node-version: [20.9.0]
                os: [ubuntu-latest, windows-latest]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Run CI checks
              run: npm run ci

    publish:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        if: ${{github.ref == 'refs/heads/main'}}
        needs: [quality]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.9.0"
                  registry-url: "https://registry.npmjs.org"
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
