# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mcp-server

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Make binary executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x dist/index.js

  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/main'}}
    needs: [quality]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Make binary executable
        run: chmod +x dist/index.js
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}